# Generated by Django 4.0 on 2023-12-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_general", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="registeredAt",
            new_name="registered_at",
        ),
    ]
